server:
  port: 8080

mybatis:
  mapper-locations:
    - classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: cn.jxufe.bean

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://47.101.223.154:3306/blog?autoReconnect=true&useUnicode=true&createDatabaseIfNotExist=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT
      username: root
      password: 123456
      initial-size: 2
      min-idle: 2
      max-active: 4
      max-wait: 10000
      test-on-borrow: true
      test-while-idle: true
        # 状态监控
      filter:
        stat:
          enabled: true
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 2000
        # 监控过滤器
      web-stat-filter:
        enabled: true
        exclusions:
          - "*.js"
          - "*.gif"
          - "*.jpg"
          - "*.png"
          - "*.css"
          - "*.ico"
          - "/druid/*"
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: 123456

  # 配置缓存
  redis:
    host: 47.101.223.154
    port: 6379
    password: 123456
    # 连接超时时间（毫秒）
    timeout: 5000
    # 默认是索引为0的数据库
    database: 0
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 3
        # 连接池中的最小空闲连接
        max-idle: 0
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 100000

#customize
cookie:
  name:
    # 即login token每个字母后移一位的结果
    token: "mphjouplfo"
    userId: "userId"

#  token过期天数
token:
  expire:
    day: 3
